### ISSUE TITLE
Pr3: `ponerN` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [pache0015/EstrD22s1#10]
Estás haciendo una mezcolanza de colores al llamar a la recursión. 
Y en el caso de celda vacía agrega una única bolita, y no las pedidas.
¿La probaste?
Además, estás mirando AMBOS parámetros, cuando alcanza con mirar uno solo.

**Comment by pache0015** [comment]
Evidentemente se me pasó probarla porque al verla tampoco entendí muy bien qué había hecho. Ya está corregida, gracias.

**Comment by fidel-ml** [comment]
Fijate que ahora usa `Bolita` en lugar de `poner` haciendo que `ponerN` dependa de la definición del tipo y no de una auxiliar que siempre va a poner...

**Comment by pache0015** [comment]
Sí, pude ver el problema. Ya está corregido, gracias!
