### ISSUE TITLE
Pr3: `cantTesorosEntre` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [pache0015/EstrD22s1#12]
Al llamar recursivamente, no estás manteniendo lo que se pide.
Si yo te pido los elementos entre 2 y 4, y vos pedís los que hay entre 1 y 4 y luego entre 0 y 4, me terminás dando lo que hay en 5 cofres, pero me tenés que dar lo que hay solamente en 3...

**Comment by pache0015** [comment]
Corregido
