### ISSUE TITLE
Pr3: falta `simplificar`

### ISSUE THREAD

**Issue by fidel-ml** [pache0015/EstrD22s1#16]
Sale por recursión estructural... ¿Te suena? ;)

**Comment by pache0015** [comment]
Ya está hecha. Gracias!

**Comment by fidel-ml** [comment]
Ahora `simplificarNeg` es incorrecta. Sería mucho mejor si se llamaste `agregarNegSiNoSeSimplifica` por ejemplo... ;)

**Comment by pache0015** [comment]
Ya está corregido, gracias
