### ISSUE TITLE
Pr2: en la funciones `losPrimeros` y `sinLosPrimeros` faltan casos

### ISSUE THREAD

**Issue by fidel-ml** [pache0015/EstrD22s1#4]
Esto hace que sean incorrectas, pues da error cuando no debería. Siempre hay que revisar que estén cubiertos TODOS los casos. Cuando hacés doble PM, es usual perder casos, por no hacerlo en forma ordenada...

**Comment by pache0015** [comment]
Gracias. Hice cambios en ambas funciones.
